services:
  # Database
  mongodb:
    image: mongo:8.0
    container_name: lokasync-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - lokasync-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lokasync-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - lokasync-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Builder (runs once and exits)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lokasync-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "80:${FRONTEND_PORT}"
      - "443:${FRONTEND_PORT}" # Forced HTTPS
    depends_on:
      - backend
    networks:
      - lokasync-network

  # Nginx Proxy Manager
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: lokasync-nginx-proxy-manager
    restart: unless-stopped
    environment:
      DB_SQLITE_FILE: /data/proxy_database.sqlite
      DISABLE_IPV6: 'true'
    ports:
      - "8080:80"
      - "8443:443"
      - "81:81" # Admin interface
    depends_on:
      - mongodb
      - backend
      - frontend
    volumes:
      - proxy_data:/data
      - proxy_ssl:/etc/letsencrypt
    networks:
      - lokasync-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  proxy_data:
    driver: local
  proxy_ssl:
    driver: local

networks:
  lokasync-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16