name: lokasync
description: "LokaSync App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0-alpha.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  sign_in_button: ^3.2.0
  google_sign_in: ^6.3.0
  elegant_notification: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  fl_chart: ^0.70.2
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Konfigurasi icon aplikasi
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_lokasync.png"
  min_sdk_android: 23
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/ic_lokasync.png"
  web:
    generate: true
    image_path: "assets/images/ic_lokasync.png"
    background_color: "#FFFFFF"
    theme_color: "#014331"
  windows:
    generate: true
    image_path: "assets/images/ic_lokasync.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/ic_lokasync.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/